### GET request to example server
PUT http://localhost:4000/patients/280ef62a-840b-4c08-a183-5525125d13ae
Content-Type: application/json

{
  "name": "Shrivatsa Joisa",
  "email": "shrivathsa.j.sj@gmail.com",
  "address": "HSR Layout",
  "dateOfBirth": "2001-07-21"
}
###